FROM node:24-alpine3.23 AS base
WORKDIR /app
ENV NPM_CONFIG_UPDATE_NOTIFIER=false \
    NPM_CONFIG_FUND=false

FROM base AS build
COPY . .
RUN npm ci && npm run build


FROM caddy:2.6-alpine AS runtime
WORKDIR /app

RUN addgroup -S webuser && adduser -S webuser -G webuser

COPY --from=build --chown=nodeapp:nodeapp /app/dist /usr/share/caddy

USER webuser
EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -q -O /dev/null http://127.0.0.1:8080/ || exit 1

CMD ["caddy", "file-server", "--root", "/usr/share/caddy", "--listen", ":8080"]
