name: ORALocal

services:
  ora-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev-server-ora
    image: ora-server
    container_name: ora-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
          ignore:
            - node_modules
