FROM node:22-alpine AS base

FROM base AS dev-deps
WORKDIR /app
COPY . .

RUN npm cache clean --force && npm install

# ORA SERVER
FROM dev-deps AS dev-server-ora
WORKDIR /app

CMD ["npm", "run", "dev:api:ora"]

# Docs Build
FROM dev-deps AS docs-build
WORKDIR /app
COPY . .

RUN npm run docs

# Docs Serve
FROM swaggerapi/swagger-ui AS docs
ENV URLS="[{url: './specs/openapi-ora.yaml', name: 'ORA API'}]"
ENV URL=""
ENV VALIDATOR_URL="none"
ENV PERSIST_AUTHORIZATION="true"
COPY --from=docs-build /app/openapi/*.yaml /usr/share/nginx/html/specs/
