name: Release Workflow

on:
  push:
    branches:
      - main
      - feat/release_workflow # TODO: Remove before merge

    paths:
      - "client/**"
      - "server/**"
      - "schema/**"
      - ".github/workflows/release.yml"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  create-tag:
    name: Bump Version and Push Tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Determine version bump
        id: bump
        run: |
          old_version=$(node -p "require('./server/package.json').version")
          IFS='.' read -r major minor patch <<< "$old_version"
          msg=$(git log -1 --pretty=%B)

          if echo "$msg" | grep -iq "#major"; then
            new_version="$((major + 1)).0.0"
          elif echo "$msg" | grep -iq "#minor"; then
            new_version="$major.$((minor + 1)).0"
          else
            new_version="$major.$minor.$((patch + 1))"
          fi

          echo "Old version: $old_version -> New version: $new_version"
          echo "version=$new_version" >> "$GITHUB_OUTPUT
      - name: Write new version to package.json files
        run: |
          node -e "
            const fs = require('fs');
            ['./server/package.json', './client/package.json'].forEach(p => {
              const pkg = JSON.parse(fs.readFileSync(p, 'utf8'));
              pkg.version = '${{ steps.bump.outputs.version }}';
              fs.writeFileSync(p, JSON.stringify(pkg, null, 2) + '\n');
            });
          "
      - name: Commit, push and tag
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git commit -am "chore: bump version to ${{ steps.bump.outputs.version }}"
          git push

          git tag "v${{ steps.bump.outputs.version }}"
          git push --tags
  # container:
  # deploy:
